dataset_type: TUMTrafV2XNuscDataset
#dataset_root: data/tumtraf_processed/
# TODO: for inference change dataset root
# NOTE: there should be a slash in the end of the folder path
dataset_root: data/tumtraf_v2x_cooperative_perception_dataset_processed/
gt_paste_stop_epoch: -1
reduce_beams: 32
load_dim: 5
use_dim: 5
load_augmented: null

point_cloud_range: [-75.0, -75.0, -8, 75.0, 75.0, 0]
voxel_size: [0.075, 0.075, 0.2]
image_size: [256, 704]

augment2d:
  resize: [[0.38, 0.55], [0.48, 0.48]]
  rotate: [-5.4, 5.4]
  gridmask:
    prob: 0.0
    fixed_prob: true

augment3d:
  scale: [0.9, 1.1]
  rotate: [-0.78539816, 0.78539816] #Try pi to pi
  translate: 0.5

object_classes:
  - CAR
  - TRAILER
  - TRUCK
  - VAN
  - PEDESTRIAN
  - BUS
  #- MOTORCYCLE
  #- OTHER
  - BICYCLE
  #- EMERGENCY_VEHICLE

input_modality:
  use_lidar: true
  use_camera: true
  use_radar: false
  use_map: false
  use_external: false

train_pipeline:
  -
    type: LoadMultiViewImageFromFilesCoop
    to_float32: true
  -
    type: LoadPointsFromFileCoop
    coord_type: LIDAR
    training: true
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    load_augmented: ${load_augmented}
  -
    type: LoadPointsFromMultiSweepsCoop
    sweeps_num: 0
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    pad_empty_sweeps: true
    remove_close: true
    load_augmented: ${load_augmented}
    training: true
  -
    type: LoadAnnotations3D
    with_bbox_3d: true
    with_label_3d: true
    with_attr_label: False
  -
    type: VehiclePointsToInfraCoords
  -
    type: ObjectPasteCoop
    stop_epoch: ${gt_paste_stop_epoch}
    db_sampler:
      dataset_root: ${dataset_root}
      # TODO: update the name of the .pck file
      info_path: ${dataset_root + "tumtraf_v2x_nusc_dbinfos_train.pkl"}
      rate: 1.0
      prepare: 
        filter_by_difficulty: [-1]
        filter_by_min_points:
          CAR: 5
          TRAILER: 5
          TRUCK: 5
          VAN: 5
          PEDESTRIAN: 5
          BUS: 5
          #MOTORCYCLE: 5
          #OTHER: 5
          BICYCLE: 5
          #EMERGENCY_VEHICLE: 5
      classes: ${object_classes}
      sample_groups:
        CAR: 2
        TRAILER: 5
        TRUCK: 3
        VAN: 3
        PEDESTRIAN: 7
        BUS: 5
        #MOTORCYCLE: 5
        #OTHER: 2
        BICYCLE: 7
        #EMERGENCY_VEHICLE: 15
      points_loader:
        type: LoadPointsFromFile
        coord_type: LIDAR
        load_dim: ${load_dim}
        use_dim: ${use_dim}
        reduce_beams: ${reduce_beams}
  -
    type: ImageAug3DCoop
    final_dim: ${image_size}
    resize_lim: ${augment2d.resize[0]}
    bot_pct_lim: [0.0, 0.0]
    rot_lim: ${augment2d.rotate}
    rand_flip: true
    is_train: true
  - # For now only rotate and translate
    type: GlobalRotScaleTransCoop
    resize_lim: ${augment3d.scale}
    rot_lim: ${augment3d.rotate}
    trans_lim: ${augment3d.translate}
    is_train: true
  #-
  #  type: RandomFlip3DCoop
  -
    type: PointsRangeFilterCoop
    point_cloud_range: ${point_cloud_range}
  -
    type: ObjectRangeFilter
    point_cloud_range: ${point_cloud_range}
  -
    type: ObjectNameFilter
    classes: ${object_classes}
  -
    type: ImageNormalizeCoop
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - 
    type: GridMaskCoop
    use_h: true
    use_w: true
    max_epoch: ${max_epochs}
    rotate: 1
    offset: false
    ratio: 0.5
    mode: 1
    prob: ${augment2d.gridmask.prob}
    fixed_prob: ${augment2d.gridmask.fixed_prob}
  -
    type: PointShuffleCoop
  -
    type: DefaultFormatBundle3DCoop
    classes: ${object_classes}
  -
    type: Collect3DCoop
    keys:
      - vehicle_img
      - infrastructure_img
      - vehicle_points
      - infrastructure_points
      - gt_bboxes_3d
      - gt_labels_3d
    meta_keys:
      - vehicle_camera_intrinsics
      - infrastructure_camera_intrinsics
      - vehicle_lidar2camera
      - infrastructure_lidar2camera
      - vehicle_camera2lidar
      - infrastructure_camera2lidar
      - vehicle_lidar2image
      - infrastructure_lidar2image
      - vehicle_img_aug_matrix
      - infrastructure_img_aug_matrix
      - vehicle_lidar_aug_matrix
      - infrastructure_lidar_aug_matrix
      - vehicle2infrastructure

val_pipeline:
  -
    type: LoadMultiViewImageFromFilesCoop
    to_float32: true
  -
    type: LoadPointsFromFileCoop
    coord_type: LIDAR
    training: false
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    load_augmented: ${load_augmented}
  -
    type: LoadPointsFromMultiSweepsCoop
    sweeps_num: 0
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    pad_empty_sweeps: true
    remove_close: true
    load_augmented: ${load_augmented}
    training: false
  -
    type: LoadAnnotations3D
    with_bbox_3d: true
    with_label_3d: true
    with_attr_label: False
  -
    type: VehiclePointsToInfraCoords
  -
    type: ImageAug3DCoop
    final_dim: ${image_size}
    resize_lim: ${augment2d.resize[1]}
    bot_pct_lim: [0.0, 0.0]
    rot_lim: [0.0, 0.0]
    rand_flip: false
    is_train: false
  -
    type: GlobalRotScaleTransCoop
    resize_lim: [1.0, 1.0]
    rot_lim: [0.0, 0.0]
    trans_lim: 0.0
    is_train: false
  -
    type: PointsRangeFilterCoop
    point_cloud_range: ${point_cloud_range}
  -
    type: ImageNormalizeCoop
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  -
    type: DefaultFormatBundle3DCoop
    classes: ${object_classes}
  -
    type: Collect3DCoop
    keys:
      - vehicle_img
      - infrastructure_img
      - vehicle_points
      - infrastructure_points
      - gt_bboxes_3d
      - gt_labels_3d
    meta_keys:
      - vehicle_camera_intrinsics
      - infrastructure_camera_intrinsics
      - vehicle_lidar2camera
      - infrastructure_lidar2camera
      - vehicle_camera2lidar
      - infrastructure_camera2lidar
      - vehicle_lidar2image
      - infrastructure_lidar2image
      - vehicle_img_aug_matrix
      - infrastructure_img_aug_matrix
      - vehicle_lidar_aug_matrix
      - infrastructure_lidar_aug_matrix
      - vehicle2infrastructure

test_pipeline:
  -
    type: LoadMultiViewImageFromFilesCoop
    to_float32: true
  -
    type: LoadPointsFromFileCoop
    coord_type: LIDAR
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    load_augmented: ${load_augmented}
    training: false
  -
    type: LoadPointsFromMultiSweepsCoop
    sweeps_num: 0
    load_dim: ${load_dim}
    use_dim: ${use_dim}
    reduce_beams: ${reduce_beams}
    pad_empty_sweeps: true
    remove_close: true
    load_augmented: ${load_augmented}
    training: false
  -
    type: VehiclePointsToInfraCoords
  -
    type: ImageAug3DCoop
    final_dim: ${image_size}
    resize_lim: ${augment2d.resize[1]}
    bot_pct_lim: [0.0, 0.0]
    rot_lim: [0.0, 0.0]
    rand_flip: false
    is_train: false
  -
    type: GlobalRotScaleTransCoop
    resize_lim: [1.0, 1.0]
    rot_lim: [0.0, 0.0]
    trans_lim: 0.0
    is_train: false
  -
    type: PointsRangeFilterCoop
    point_cloud_range: ${point_cloud_range}
  -
    type: ImageNormalizeCoop
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  -
    type: DefaultFormatBundle3DCoop
    classes: ${object_classes}
  -
    type: Collect3DCoop
    keys:
      - vehicle_img
      - infrastructure_img
      - vehicle_points
      - infrastructure_points
    meta_keys:
      - vehicle_camera_intrinsics
      - infrastructure_camera_intrinsics
      - vehicle_lidar2camera
      - infrastructure_lidar2camera
      - vehicle_camera2lidar
      - infrastructure_camera2lidar
      - vehicle_lidar2image
      - infrastructure_lidar2image
      - vehicle_img_aug_matrix
      - infrastructure_img_aug_matrix
      - vehicle_lidar_aug_matrix
      - infrastructure_lidar_aug_matrix
      - vehicle2infrastructure

data:
  samples_per_gpu: 4
  workers_per_gpu: 4
  train:
    type: CBGSDataset
    dataset:
      type: ${dataset_type}
      dataset_root: ${dataset_root}
      # TODO: update the name of .pcl file
      ann_file: ${dataset_root + "tumtraf_v2x_nusc_infos_train.pkl"}
      pipeline: ${train_pipeline}
      object_classes: ${object_classes}
      modality: ${input_modality}
      test_mode: false
      use_valid_flag: true
      box_type_3d: LiDAR
  val:
    type: ${dataset_type}
    dataset_root: ${dataset_root}
    # TODO: update the name of .pcl file
    ann_file: ${dataset_root + "tumtraf_v2x_nusc_infos_val.pkl"}
    pipeline: ${val_pipeline}
    object_classes: ${object_classes}
    modality: ${input_modality}
    test_mode: false
    box_type_3d: LiDAR
  test:
    type: ${dataset_type}
    dataset_root: ${dataset_root}
    # TODO: update the name of .pcl file
    ann_file: ${dataset_root + "tumtraf_v2x_nusc_infos_test.pkl"}
    pipeline: ${test_pipeline}
    object_classes: ${object_classes}
    modality: ${input_modality}
    test_mode: true
    box_type_3d: LiDAR

evaluation:
  interval: 1
  pipeline: ${test_pipeline}
 
